
server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pl_portal
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

#    show-sql: true

